---
title: "CapStone"
author: "Laura Lazarescou, Tina Pai, Andrew Mejia, Sabrina Purvis"
date: "`r Sys.time()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
  github_document:
    toc: yes
    toc_depth: 6
  word_document:
    toc: yes
    toc_depth: '6'
always_allow_html: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE, warning=FALSE, options("rgdal_show_exportToProj4_warnings"="none")}
library(tidyverse)
library(rpart)
library(tm)
library(tidyverse)
library(randomForest)
library(caret)
library(knitr)
library(kableExtra)
library(XML)
library(stringr)
library(dplyr)
library(corrplot)
library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
library(dplyr)
library(ggraph)
library(igraph)
library(e1071)
library(ROCR)
library(DiagrammeR)
library(doSNOW)
library(parallel)
library(ggplot2)
library(xgboost)
library(rgdal)
```

```{r}


# The input file geodatabase
fgdb = "/media/andrew/Seagate Backup Plus Drive/Documents/School/HomeWork/Capstone/Vacant Lot Analysis.gdb"

# List all feature classes in a file geodatabase
subset(ogrDrivers(), grepl("GDB", name))
fc_list <- ogrListLayers(fgdb)
print(fc_list)

ogrListLayers(fgdb)

# Read the feature class
fc <- readOGR(dsn=fgdb,layer=ogrListLayers(fgdb)[1])

# Determine the FC extent, projection, and attribute information
summary(fc)

# View the feature class
plot(fc)

```
