 head -1000 account_apprl_year.csv > account_apprl_year_small.csv
 head -1000 account_info.csv > account_info_small.csv
 head -1000 account_tif.csv > account_tif_small.csv
 head -1000 account_info.csv > account_info_small.csv
 head -1000 acct_exempt_value.csv > acct_exempt_value_small.csv
 head -1000 applied_std_exempt.csv > applied_std_exempt_small.csv
 head -1000 com_detail.csv > com_detail_small.csv
 head -1000 land.csv > land_small.csv
 head -1000 multi_owner.csv > multi_owner_small.csv
 head -1000 res_addl.csv > res_addl_small.csv
 head -1000 res_detail.csv > res_detail_small.csv
 head -1000 taxable_object.csv > taxable_object_small.csv