---
title: "CapStone"
author: "Laura Lazarescou, Tina Pai, Andrew Mejia, Sabrina Purvis"
date: "`r Sys.time()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
  github_document:
    toc: yes
    toc_depth: 6
  word_document:
    toc: yes
    toc_depth: '6'
always_allow_html: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=FALSE, warning=FALSE, options("rgdal_show_exportToProj4_warnings"="none")}
library(tidyverse)
library(rpart)
library(tm)
library(tidyverse)
library(randomForest)
library(caret)
library(knitr)
library(XML)
library(stringr)
library(dplyr)
library(corrplot)
library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
library(dplyr)
library(ggraph)
library(igraph)
library(e1071)
library(ROCR)
library(DiagrammeR)
library(doSNOW)
library(parallel)
library(ggplot2)
library(xgboost)
library(rgdal)
library(rgeos)
library(raster)
library(sp)
library(ggmap)
```

```{r}
setwd("/home/andrew/Desktop/Dallas Files/")
file_direct = '/home/andrew/Desktop/Dallas Files/GIS_PACKAGE_FILES_TO_CSV/' 

#Shape layer of all parcels in the City of Dallas
clipped_parcels_by_dallas_geomtry = read.csv(file=paste0(file_direct,'Clipped_Parcels_by_Dallas_Simple.csv'))

#All of Dallas County Parcels 
DCAD_aprl_year = read.table(unz("DCAD2019_CURRENT.ZIP", "account_apprl_year.csv"), sep = ",", header = TRUE)

#These are the only accounts in the Dallas city limits 
DCAD_aprl_year_filtered_by_clipped_parcels = clipped_parcels_by_dallas_geomtry %>% inner_join(DCAD_aprl_year, by = c("Acct"="ACCOUNT_NUM"))

dim(DCAD_aprl_year[duplicated(DCAD_aprl_year$ACCOUNT_NUM),])[1]
#You would want to use caution eliminate the parcels since these are multi-use buildings 
#00000300268000000 with account 0000030026800TE00	
dim(DCAD_aprl_year[duplicated(DCAD_aprl_year$GIS_PARCEL_ID),])[1]
head(DCAD_aprl_year[duplicated(DCAD_aprl_year$GIS_PARCEL_ID),], n = 20)

###CPAL Annotations
CPAL_Label_annotations = read.csv(file=paste0(file_direct,'Clipped_Parcels_by_Dallas_Simple_vac_pts_annotations.csv'))
CPAL_Label_annotations["VAC_PAR"] = 1

dim(CPAL_Label_annotations [duplicated(CPAL_Label_annotations $ACCOUNT_NUM),])[1]
#You would want to use caution eliminate the parcels since these are multi-use buildings 
#00000300268000000 with account 0000030026800TE00	
dim(CPAL_Label_annotations [duplicated(CPAL_Label_annotations $GIS_PARCEL_ID),])[1]
head(CPAL_Label_annotations [duplicated(CPAL_Label_annotations $GIS_PARCEL_ID),], n = 20)

### Join to DCAD FILTERED BY PARCELS TO CPAL ANNOTATIONS
DCAD_aprl_year_filtered_by_clipped_parcels_annotated = full_join(DCAD_aprl_year_filtered_by_clipped_parcels,CPAL_Label_annotations, by = c("Acct" = "Acct"), suffix = c(".x", ".y"), keep = TRUE)

### Add remaing target labels
DCAD_aprl_year_filtered_by_clipped_parcels_annotated['VAC_PAR'] = ifelse(is.na(DCAD_aprl_year_filtered_by_clipped_parcels_annotated$VAC_PAR),0, DCAD_aprl_year_filtered_by_clipped_parcels_annotated$VAC_PAR) 

#Size of not vacant
dim(DCAD_aprl_year_filtered_by_clipped_parcels_annotated %>% filter(VAC_PAR == 0))
#Size of Vacant
dim(DCAD_aprl_year_filtered_by_clipped_parcels_annotated %>% filter(VAC_PAR == 1))
#size of CPAL annotations
dim(CPAL_Label_annotations)

### 311 
Clipped_311_2019 = read.csv(file=paste0(file_direct,'Clipped_Parcels_by_Dallas_Simple_inner_join_to_Clipped_2019_311.csv'))

DCAD_aprl_year_filtered_by_clipped_parcels_annotated_joined_to_311 = full_join(DCAD_aprl_year_filtered_by_clipped_parcels_annotated,Clipped_311_2019,by = c("Acct.x" = "Acct"), suffix = c(".x", ".y"), keep = TRUE )
  
#### Crime 
Clipped_All_Crime_2019 = read.csv(file=paste0(file_direct,'Clipped_Parcels_by_Dallas_Simple_inner_join_to_Clipped_2019_Police_Incidents.csv'))

### CO 
Clipped_CO_2019 = read.csv(file=paste0(file_direct,'Clipped_Parcels_by_Dallas_Simple_inner_join_to_Clipped_2019_co.csv'))
Clipped_CO_2019['CO_ON_ACCOUNT'] = 1

DCAD_aprl_year_filtered_by_clipped_parcels_annotated_joined_to_co = full_join(DCAD_aprl_year_filtered_by_clipped_parcels_annotated,Clipped_CO_2019,by = c("Acct.x" = "Acct"), suffix = c(".x", ".y"), keep = TRUE )

DCAD_aprl_year_filtered_by_clipped_parcels_annotated_joined_to_co['CO_ON_ACCOUNT'] = ifelse(is.na(DCAD_aprl_year_filtered_by_clipped_parcels_annotated_joined_to_co$CO_ON_ACCOUNT), 0, 1)

#Get a count of accounts with a CO
DCAD_aprl_year_filtered_by_clipped_parcels_annotated_joined_to_co %>% group_by(Acct.x) %>% tally(CO_ON_ACCOUNT)

```

